[programs.devnet]
myepicproject = "9tVzx7kP2VSd6sMsEsLHDepFfGHpXhWcRABNgHxF4xkT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/robbie/.config/solana/id.json"

[scripts]
test = "npx mocha tests/myepicproject.js"
